version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-query
    versions:
    - 3.11.0
    - 3.12.0
    - 3.12.1
    - 3.12.2
    - 3.12.3
    - 3.13.0
    - 3.13.10
    - 3.13.11
    - 3.13.2
    - 3.13.4
    - 3.13.5
    - 3.13.6
    - 3.13.7
    - 3.13.8
    - 3.6.0
    - 3.6.1
    - 3.7.1
    - 3.8.2
    - 3.8.3
    - 3.9.6
    - 3.9.7
    - 3.9.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
